Prevents Stale Datagrams from exhausting server memory
NukkitX/Network pull request #25
Opened 2021-08-19 06:09 UTC by nirui

This path caps the maximum allowed Stale Datagrams a RakNetSession can hold to 256, the client must ACK received datagrams to stay within this limit, otherwise it will be disconnected.

As far as I can tell, before this path, the client can stay connected without necessarily clear all the datagrams that it has received (`touch` can be called by `onDatagram` without calling `onAcknowledge`), which allows the client to slowly consumes all the memory of the server, causing crash and maybe DoS attack.

2021-08-19 06:51 UTC, nirui commented
Resolving conflicts, please hold ...

2021-08-19 08:26 UTC, nirui commented
Conflicts are resolved. 

I was working on the `master` branch and never noticed the activities are actually happening in `develop`.

I also retested the new `RakNetSession` from the dev branch, it does not invalidate this patch.

2021-08-19 08:57 UTC, rtm516 requested changes

2021-08-19 08:57 UTC, rtm516 commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetSession.java
> +        }
```suggestion
        }

```

2021-08-19 09:07 UTC, nirui commented on raknet/src/main/java/com/nukkitx/network/raknet/RakNetSession.java
> +        }
Implemented.

2021-10-09 18:25 UTC, SupremeMortal approved these changes

2021-10-09 18:25 UTC, merged