Add Compatibility Mode
NukkitX/Network pull request #43
Opened 2024-05-13 02:45 UTC by Kas-tle

Adds a compatibility mode option to prevent crashes and disconnections by bringing behavior closer in line with the vanilla client. Closes https://github.com/CloudburstMC/Network/issues/41, https://github.com/CloudburstMC/Network/issues/34, https://github.com/CloudburstMC/Network/issues/33, and https://github.com/CloudburstMC/Network/issues/30.

2024-05-16 11:23 UTC, Alemiz112 requested changes

2024-05-16 11:23 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakSessionConfig.java
> +                RakChannelOption.RAK_METRICS, RakChannelOption.RAK_SESSION_TIMEOUT, RakChannelOption.RAK_AUTO_FLUSH, RakChannelOption.RAK_FLUSH_INTERVAL, RakChannelOption.RAK_COMPATIBILITY_MODE);
It would be better to move this to client-only config class because this option should not affect server connections.

2024-05-16 11:23 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/handler/codec/raknet/client/RakClientOnlineInitialHandler.java
> +            count = 20;
Might be worth to explain why

2024-05-16 13:52 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/handler/codec/raknet/client/RakClientOnlineInitialHandler.java
> +            count = 20;
It's just what the vanilla client does based on connecting to multiple servers observed in WireShark. I am not sure where the current choice of using the number of addresses in the previous packet came from in the first place as in the original RakNet it is hard coded as well (albeit at 10). I am assuming it's a consistent number as Mineville disconnects if it is not exactly 20.
https://github.com/facebookarchive/RakNet/blob/master/Source/RakNetDefines.h#L76
https://github.com/facebookarchive/RakNet/blob/master/Source/RakPeer.cpp#L6196-L6197

2024-05-16 13:53 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakSessionConfig.java
> +                RakChannelOption.RAK_METRICS, RakChannelOption.RAK_SESSION_TIMEOUT, RakChannelOption.RAK_AUTO_FLUSH, RakChannelOption.RAK_FLUSH_INTERVAL, RakChannelOption.RAK_COMPATIBILITY_MODE);
Ok will do.

2024-05-16 14:09 UTC, Kas-tle commented
### TODO
- Reflect on if [`jdk.net.ExtendedSocketOptions#IP_DONTFRAGMENT`](https://github.com/openjdk/jdk/blob/master/src/jdk.net/share/classes/jdk/net/ExtendedSocketOptions.java#L226-L227) is available (see https://github.com/openjdk/jdk/blob/master/test/jdk/java/net/SocketOption/AfterClose.java#L108-L109) and if yes enable channel option.
- If not and if Unix, try to manually construct and enable a Unix socket option for `IP_DONTFRAG` (see https://github.com/CloudburstMC/Network/commit/f231b1f82d1269da545e5ef34822978ac6b88fe7)
- If none of these, warn that packet fragmentation could not be disabled.

2024-05-19 15:18 UTC, Alemiz112 requested changes

2024-05-19 15:18 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/RakClientChannel.java
> +        if (!IpDontFragmentProvider.trySet(this)) {
IP_DONT_FRAGMENT should not be enabled by default. It does cause connection issues in several cases such as, but not limited to when connecting over VPN or when using VM.

2024-05-19 15:18 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/RakConstants.java
> +    public static final int MAXIMUM_MTU_SIZE = 1492;
The maximum MTU was decreased  here intentionally to prevent connection issues with certain tunneled connections iirc.

2024-05-23 08:37 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakClientConfig.java
> +            RakChannelOption.RAK_MTU_SIZES, RakChannelOption.RAK_IP_DONT_FRAGMENT, RakChannelOption.RAK_CLIENT_INTERNAL_ADDRESSES);
I just noticed this is client only - It would be nice if we could also set this option on server channel too.

2024-06-17 01:06 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakClientConfig.java
> +            RakChannelOption.RAK_MTU_SIZES, RakChannelOption.RAK_IP_DONT_FRAGMENT, RakChannelOption.RAK_CLIENT_INTERNAL_ADDRESSES);
Fixed.

2024-06-18 18:43 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/RakConstants.java
> +    public static final int MAXIMUM_MTU_SIZE = 1492;
Reverted.

2024-06-18 18:43 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/RakClientChannel.java
> +        if (!IpDontFragmentProvider.trySet(this)) {
Set to false by default now.

2024-06-18 18:44 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/handler/codec/raknet/client/RakClientOnlineInitialHandler.java
> +            count = 20;
Now can be configured.

2024-07-04 15:35 UTC, Alemiz112 requested changes

2024-07-04 15:35 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakServerConfig.java
> +        this.ipDontFragment = ipDontFragment ? IpDontFragmentProvider.trySet(this.channel.parent()) : false;
What will happen if we call `setIpDontFragment(true)` and then `setIpDontFragment(false)`? Are you sure it will get into the same state as if `setIpDontFragment()` was not even called? - i.e. will something actually "unset" the option.

2024-07-04 15:35 UTC, Alemiz112 commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakClientConfig.java
> +        this.ipDontFragment = enable ? IpDontFragmentProvider.trySet(this.channel) : false;
What will happen if we call `setIpDontFragment(true)` and then `setIpDontFragment(false)`? Are you sure it will get into the same state as if `setIpDontFragment()` was not even called? - i.e. will something actually "unset" the option.

2024-07-04 21:56 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakServerConfig.java
> +        this.ipDontFragment = ipDontFragment ? IpDontFragmentProvider.trySet(this.channel.parent()) : false;
Made so it can be set to false.

2024-07-04 21:57 UTC, Kas-tle commented on transport-raknet/src/main/java/org/cloudburstmc/netty/channel/raknet/config/DefaultRakClientConfig.java
> +        this.ipDontFragment = enable ? IpDontFragmentProvider.trySet(this.channel) : false;
Made so it can be set to false.

2024-07-08 18:17 UTC, Alemiz112 approved these changes
All looks good. Thanks!

2024-07-08 18:19 UTC, merged